= SScript scripting Library for Arduino =

* SScript is a relatively high performance scripting library.
* The library enables the use of gustom c++ functions easily.
* The compiler is coded in python for ease of use.
* The 'intepreter' is coded in c++ for performance.


### Hello world

#### Script file:

```python
"""Print in a loop."""
from src.SProgram import SProgram as program


def main():
    """Print 'Hello world!' int(count) in a loop."""
    # program
    p = program(
        variableNameValuePairs=[
            # initialize count = 0
            "count"
            # initialize count = 1
            # ("count", 1)
            # create list("count", 3) (= count[0], count[1], count[2])
            # ["count", 3]
        ],
        # set strings
        stringNameValuePairs=[
            ("helloworld_str", "Hello world! "),
        ],
        # set frames/second = 1
        #   (How to set fps for invidual states: See timerTest)
        #   (i.e., simple multithreading)
        fps=1,
        # program (state, [expressions])
        program=[
            ("main", [
                # increase count by one
                ["inc", "count"],
                # print("Hello world!", endl=False)
                ["printString", "helloworld_str"],
                # print(count, endl = True)
                ["printInt", "count", True],
            ])
        ])
    # compile and print the program
    p.compile()


if __name__ == "__main__":
    # execute only if run as a script
    main()
```

#### Script compilation:

```bash
$ python3 simpleHelloworld.py

INITIALIZING PROGRAM...

states:
('main', [['readTimer'], ['timeout', '_lastTimedOut', '_timeoutLength'], ['inc', 'count'], ['printString', 'helloworld_str'], ['printInt', 'count', True]])

variables:
[['_lastTimedOut', ('_timeoutLength', 1000), 'count'], [('helloworld_str', 'Hello world! ')]]

PROGRAM INITIALIZED

COMPILING...

states:1
 state(0) expressions: 5
   expression(0) elements: 1 [13]
   expression(1) elements: 3 [27 28 15]
   expression(2) elements: 3 [29 3 0]
   expression(3) elements: 3 [2 30 29]
   expression(4) elements: 3 [2 29 28]

COMPILED...

31 3 3 1 4 0 28 1000 1 1 0 Hello world! ; 1 5 1 13 3 27 28 15 3 29 3 0 3 2 30 29 3 2 29 28

```

##### C++ file (example)

```c++
#include <iostream>
#include "SScript.h"
// ESPConfiguration can be changed to another
// The configuration file must provide extern
// functions, nothing else.
// see https://github.com/alklasil/ESP/blob/master/teensySoftware/teensySoftware/ESPConfiguration.cpp
// for more detail
#include "ESPConfiguration.h"

// example usage:
// ./main "31 3 3 1 4 0 28 1000 1 1 0 Hello world! ; 1 5 1 13 3 27 28 15 3 29 3 0 3 2 30 29 3 2 29 28"

int main(int argc, char* argv[])
{

  if (argc < 2) {
     printf("Usage: %s %s \n", argv[0], "<CONFIGURATION>");
     return 1;
  }

  void(*(*_functions))(int32_t *leftValue, int32_t *rightValue) = functions;

  sScript.setFunctions(_functions);
  char buffer[1024];
  strcpy(buffer, argv[1]);
  sScript.set(buffer);
  // HOX! when setting sScript. the buffer is destroyed
  // If there is a change you may need to reuse the configuration,
  // Do copy it somewhere safe first.
  //  (This approach was chosen due to having limited memory in arduino devices)
  //  (This may change in the future to be optional depending on need and time)

  while (1) {
      // do here what ever you want!
      // for example: check if there are requests for a web page.
      //              or do what ever it is that needs doing.

      sScript.loop();
  }
}
```

#### C++ compile
Platform depended. Can be compiled for arduino and linux (windows not supported yet).
 
#### (C++ test) compile (example)

```bash
$ g++ *.cpp ../src/*.cpp <Other files (such as configuration.cpp, sensors.cpp, etc), depends> -std=c++11 -I ../src -I <Other paths> -o main
```

#### (C++ test) run (DEBUG disabled)

```c++
$ ./main '31 3 3 1 4 0 28 1000 1 1 0 Hello world! ; 1 5 1 13 3 27 28 15 3 29 3 0 3 2 30 29 3 2 29 28'
Hello world! 1
Hello world! 2
Hello world! 3
Hello world! 4
Hello world! 5
Hello world! 6
Hello world! 7
Hello world! 8
Hello world! 9
Hello world! 10
Hello world! 11
Hello world! 12
Hello world! 13
Hello world! 14
Hello world! 15
...
```

#### Performance

* HOX! Performance depends on the platform, the script used and the SScript version used. 
* HOX! Printing the characters to the concole slows the execution down.
* HOX! The script file was modified (fps=None, which means there is no active fps limiter). 

##### On a laptop
 * Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
 * Ubuntu 16.04

```bash
$ time ./main '29 2 3 1 4 0 1 1 0 Hello world! ; 1 3 3 27 3 0 3 2 28 29 3 2 27 28'
...
Hello world! 3465647
Hello world! 3465648
Hello world! 3465649
Hello world! 3465650
Hello world! 3465651
Hello world! 3465652
Hello world! 3465653
Hello world! 3465654
Hello world! 3465655
Hello world! 3465656
Hello world! ^C

real	0m26.989s
user	0m3.702s
sys	0m15.792s
```

###### On a teensy3.2 board (coming...)


#### Example configuration file (provided in a configuration c++ file, e.g., configuration.cpp)

* Configuration file provides the functions for SScript.
* HOX! all the functions definitions are not shown. 

*ESPConfiguration.cpp*
```c++
#include "ESPConfiguration.h"

void add(int32_t *leftValue, int32_t *rightValue) { *leftValue += *rightValue; }
void sub(int32_t *leftValue, int32_t *rightValue) { *leftValue -= *rightValue; }
....
void readTimer(int32_t *leftValue, int32_t *rightValue) { ... }
...

void(*functions[])(int32_t *leftValue, int32_t *rightValue) = {
    add,
    sub,
    ...
    readTimer,
    ...
};
```
*ESPConfiguration.h*
```c++
...
extern void(*functions[])(int32_t *leftValue, int32_t *rightValue);
...
```

 * The functions must match the SScript functions defined in STDSfunctions.py and vise versa (at least the order of functions, not neseccarily the names).
 * The functions in STDSfunctions.py are for now hardcoded, this will change in the future. 

*STDSFunctions.py*
```python
...
            self.f = sl([
                sf("+"),                # leftValue += righValue
                sf("-"),
                ...
                sf("readTimer"),
                ...
            ])
...
```

*How to use the functions and configure the device:*

 * HOX! see the c++ (example) file above

```c++
...
  void(*(*_functions))(int32_t *leftValue, int32_t *rightValue) = functions;
  sScript.setFunctions(_functions);
  
  sScript.set(configuration_str); // where configuration_str might be '29 2 3 1 4 0 1 1 0 Hello world! ; 1 3 3 27 3 0 3 2 28 29 3 2 27 28'
```





For more information about this library please visit us at
https://github.com/alklasil/SScript

== License ==

Copyright (c) Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
